## Fun with unpacking

In [1]:
# Python3 code to demonstrate working of
# Unpack whole list into variables
# using Namedtuple
from collections import namedtuple
  
# initialize list
test_list = [1, 3, 7, 4, 2]
  
# printing original list
print("The original list is : " + str(test_list))
  
# Unpack whole list into variables
# using Namedtuple
temp = namedtuple("temp", "one two three four five")
res = temp(*test_list)
  
# printing result
print("Variables as assigned are : " + str(res.one) + " "
                                     + str(res.two) + " "
                                     + str(res.three) + " "
                                     + str(res.four) + " "
                                     + str(res.five))

The original list is : [1, 3, 7, 4, 2]
Variables as assigned are : 1 3 7 4 2


In [2]:
res

temp(one=1, two=3, three=7, four=4, five=2)

In [2]:

# A sample function that takes 4 arguments
# and prints the,
def fun(a, b, c, d):
    print(a, b, c, d)
 
# Driver Code
my_list = [1, 2, 3, 4]
 
# Unpacking list into four arguments
fun(*my_list)

1 2 3 4


In [4]:
*my_list

SyntaxError: can't use starred expression here (<ipython-input-4-913a8f661fc3>, line 4)

In [4]:
# Error when len(args) != no of actual arguments
# required by the funcntion
 
args = [0, 1, 4, 9]
 
 
def func(a, b, c):
    return a + b + c
 
 
# calling function with unpacking args
func(*args)

TypeError: func() takes 3 positional arguments but 4 were given

In [5]:
import numpy as np

arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])
print(arr)

flat_array = arr.flatten()
print('1D Numpy Array:')
print(flat_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1D Numpy Array:
[0 1 2 3 4 5 6 7 8]
